name: meshcnn
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.6.8
  - cython=0.27.3
  - pytorch=1.2.0
  - numpy=1.15.0
  - matplotlib=3.0.3
  - pip
  - trimesh=3.22.5
  - scipy=1.11.1
  - pip:
    - git+https://github.com/lanpa/tensorboardX.git
    - pytest==5.1.1
